#!/usr/bin/env php
<?php
require __DIR__."/vendor/autoload.php";

use App\CreateUserCommand;
use App\DumpDeps;
use App\GenerateClass;
use Symfony\Component\Console\Application;

$aplication = new Application();
$aplication->add(new DumpDeps());
$aplication->add(new GenerateClass());
$aplication->run();
